# Generated by Django 5.2.17 on 2026-08-08 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('records', '0005_canonicalresult_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='records.achievement'),
        ),
    ]
