# Generated by Django 5.2.17 on 2026-08-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationevent_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationevent',
            name='achievement',
        ),
    ]
