# Generated by Django 5.2.17 on 2026-08-30 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notificationevent_achievement'),
        ('records', '0016_baselinemetadata_baselinerecordsaverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='processed_record_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='records.processedresultrecordlevel'),
        ),
    ]
