# Generated by Django 5.2.17 on 2026-08-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wca_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=2)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date', 'name'],
            },
        ),
    ]
