# Generated by Django 5.2.17 on 2026-08-04 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('subscription', 'Subscription'), ('reconciliation', 'Reconciliation')], max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('observations_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('event_id', models.CharField(max_length=16)),
                ('event_name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('single', 'Single'), ('average', 'Average')], max_length=8)),
                ('value', models.IntegerField(help_text='Integer-encoded value received from the source')),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.competition')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitors.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('WR', 'World'), ('CR', 'Continental'), ('NR', 'National')], max_length=2)),
                ('detected_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn')], default='active', max_length=10)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='records.result')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='wca_live', max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(max_length=128)),
                ('observed_at', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('ingestion_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='records.ingestionrun')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
    ]
