# Generated by Django 5.2.17 on 2026-08-08 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_notification_competition_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_key', models.CharField(max_length=768, unique=True)),
                ('wca_competition_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('competition_name', models.CharField(max_length=255)),
                ('competition_country_code', models.CharField(blank=True, max_length=8)),
                ('competition_start_date', models.DateField(blank=True, null=True)),
                ('competition_end_date', models.DateField(blank=True, null=True)),
                ('round_id', models.CharField(blank=True, max_length=64)),
                ('round_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('round_name', models.CharField(blank=True, max_length=128)),
                ('event_id', models.CharField(db_index=True, max_length=16)),
                ('event_name', models.CharField(max_length=128)),
                ('competitor_name', models.CharField(max_length=255)),
                ('competitor_wca_id', models.CharField(blank=True, db_index=True, max_length=16)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('kind', models.CharField(choices=[('single', 'Single'), ('average', 'Average')], max_length=8)),
                ('attempt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('value', models.IntegerField()),
                ('formatted_result', models.CharField(max_length=128)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('first_observed_at', models.DateTimeField()),
                ('last_observed_at', models.DateTimeField()),
                ('source_url', models.URLField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('active', 'Active'), ('corrected', 'Corrected'), ('retracted', 'Retracted')], default='active', max_length=16)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('validation_reason', models.CharField(blank=True, max_length=128)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-entered_at', '-first_observed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WR', 'World record'), ('CR', 'Continental record'), ('NR', 'National record'), ('PR', 'Personal record')], max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn')], default='active', max_length=16)),
                ('classification_reason', models.CharField(max_length=64)),
                ('source_claim_supported', models.BooleanField(default=False)),
                ('benchmark_value', models.IntegerField(blank=True, null=True)),
                ('classified_at', models.DateTimeField()),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='records.canonicalresult')),
            ],
            options={
                'ordering': ['-classified_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='recentrecordobservation',
            name='canonical_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_record_projections', to='records.canonicalresult'),
        ),
        migrations.CreateModel(
            name='PersonalBestBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_wca_id', models.CharField(max_length=16)),
                ('event_id', models.CharField(max_length=16)),
                ('kind', models.CharField(choices=[('single', 'Single'), ('average', 'Average')], max_length=8)),
                ('value', models.IntegerField()),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('competitor_wca_id', 'event_id', 'kind'), name='unique_personal_best_baseline')],
            },
        ),
        migrations.CreateModel(
            name='QualificationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('homepage_category', models.CharField(blank=True, max_length=2)),
                ('notification_eligible', models.BooleanField(default=False)),
                ('homepage_reason', models.CharField(blank=True, max_length=128)),
                ('notification_reason', models.CharField(blank=True, max_length=128)),
                ('evaluated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='records.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='RecordBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('WR', 'World'), ('CR', 'Continental'), ('NR', 'National')], max_length=2)),
                ('event_id', models.CharField(max_length=16)),
                ('kind', models.CharField(choices=[('single', 'Single'), ('average', 'Average')], max_length=8)),
                ('region_code', models.CharField(blank=True, help_text='Empty for WR, continent name for CR, ISO country code for NR', max_length=64)),
                ('value', models.IntegerField()),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('level', 'event_id', 'kind', 'region_code'), name='unique_record_benchmark_scope')],
            },
        ),
        migrations.CreateModel(
            name='ResultObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_key', models.CharField(max_length=768, unique=True)),
                ('source', models.CharField(choices=[('wca_live', 'WCA Live'), ('cubingchina', 'CubingChina')], max_length=32)),
                ('ingestion_method', models.CharField(max_length=32)),
                ('source_result_identity', models.CharField(max_length=255)),
                ('source_competition_id', models.CharField(blank=True, max_length=64)),
                ('source_competitor_id', models.CharField(blank=True, max_length=64)),
                ('kind', models.CharField(choices=[('single', 'Single'), ('average', 'Average')], max_length=8)),
                ('attempt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('value', models.IntegerField()),
                ('source_record_tag', models.CharField(blank=True, max_length=8)),
                ('source_claim_trusted', models.BooleanField(default=False)),
                ('result_evidence_trusted', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('first_observed_at', models.DateTimeField()),
                ('last_observed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('retracted', 'Retracted')], default='active', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='records.canonicalresult')),
                ('raw_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_results', to='records.sourceobservation')),
            ],
            options={
                'ordering': ['-last_observed_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='canonicalresult',
            name='current_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_results', to='records.resultobservation'),
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(fields=('result', 'type'), name='unique_achievement_per_result'),
        ),
        migrations.AddIndex(
            model_name='resultobservation',
            index=models.Index(fields=['source', 'ingestion_method', 'source_result_identity'], name='result_observation_source_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalresult',
            index=models.Index(fields=['event_id', 'kind', 'status'], name='canonical_result_scope_idx'),
        ),
    ]
