# Generated by Django 5.2.17 on 2026-08-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0007_resultidentityscope_canonicalresult_identity_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="WCARecordSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(max_length=512)),
                ("payload_hash", models.CharField(max_length=64, unique=True)),
                ("records", models.JSONField(default=dict)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("first_fetched_at", models.DateTimeField()),
                ("last_fetched_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-last_fetched_at", "-id"]},
        ),
        migrations.CreateModel(
            name="RecordValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validator",
                    models.CharField(
                        choices=[("wca_records_api", "WCA records API")], max_length=32
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("WR", "World"), ("CR", "Continental"), ("NR", "National")],
                        max_length=2,
                    ),
                ),
                ("region_code", models.CharField(blank=True, max_length=64)),
                ("result_value", models.IntegerField()),
                ("benchmark_value", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("verified", "Verified"), ("rejected", "Rejected")],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(max_length=128)),
                ("checked_at", models.DateTimeField()),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_validations",
                        to="records.canonicalresult",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validations",
                        to="records.wcarecordsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["result_id", "level"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("result", "validator", "level"),
                        name="unique_record_validation_per_validator_level",
                    )
                ],
            },
        ),
    ]
