# Generated by Django 5.2 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0008_wcarecordsnapshot_recordvalidation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationScopeWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=16)),
                (
                    "kind",
                    models.CharField(
                        choices=[("single", "Single"), ("average", "Average")],
                        max_length=8,
                    ),
                ),
                ("requested_version", models.PositiveBigIntegerField(default=0)),
                ("processed_version", models.PositiveBigIntegerField(default=0)),
                ("dirty_since", models.DateTimeField(blank=True, null=True)),
                ("oldest_observed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "not_before",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("claimed_by", models.CharField(blank=True, max_length=128)),
                (
                    "claim_expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("last_result_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["dirty_since", "not_before"],
                        name="classification_work_ready_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_id", "kind"),
                        name="unique_classification_scope_work",
                    )
                ],
            },
        ),
    ]
