# Generated by Django 5.2.17 on 2026-08-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_baselinemetadata_baselinerecordsaverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalresult',
            name='timezone_resolution_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='canonicalresult',
            name='timezone_resolution_status',
            field=models.CharField(default='unresolved', max_length=16),
        ),
        migrations.AddField(
            model_name='canonicalresultrevision',
            name='timezone_resolution_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='canonicalresultrevision',
            name='timezone_resolution_status',
            field=models.CharField(default='unresolved', max_length=16),
        ),
        migrations.AddField(
            model_name='processedresult',
            name='timezone_resolution_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='processedresult',
            name='timezone_resolution_status',
            field=models.CharField(default='unresolved', max_length=16),
        ),
    ]
