# Generated by Django 5.2.17 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0017_canonicalresult_timezone_resolution_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_id", models.BigIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("single", "Single"), ("average", "Average")],
                        max_length=8,
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("value", models.IntegerField()),
                ("person_id", models.CharField(max_length=16)),
                ("event_id", models.CharField(max_length=16)),
                ("country_id", models.CharField(max_length=64)),
                ("competition_id", models.CharField(max_length=64)),
                ("round_id", models.CharField(blank=True, max_length=64, null=True)),
                ("round_type_id", models.CharField(max_length=8)),
                ("achieved_date", models.DateField()),
            ],
            options={
                "db_table": "historical_results",
                "indexes": [
                    models.Index(
                        fields=["person_id", "event_id", "kind", "achieved_date"],
                        name="hist_person_event_date_idx",
                    ),
                    models.Index(
                        fields=["event_id", "kind", "achieved_date", "value"],
                        name="hist_event_kind_date_value_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["single", "average"])),
                        name="hist_valid_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("value__gt", 0)),
                        name="hist_positive_value",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("attempt_number__isnull", True), ("kind", "average")),
                            models.Q(
                                ("attempt_number__gte", 1),
                                ("attempt_number__isnull", False),
                                ("attempt_number__lte", 5),
                                ("kind", "single"),
                            ),
                            _connector="OR",
                        ),
                        name="hist_kind_attempt_shape",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "single")),
                        fields=("result_id", "attempt_number"),
                        name="hist_unique_single_attempt",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "average")),
                        fields=("result_id",),
                        name="hist_unique_average",
                    ),
                ],
            },
        ),
    ]
