import pycountry

CONTINENTS = (
    "Africa",
    "Asia",
    "Europe",
    "North America",
    "South America",
    "Oceania",
)

AFRICA = frozenset(
    [
        "DZ",
        "AO",
        "BJ",
        "BW",
        "BF",
        "BI",
        "CV",
        "CM",
        "CF",
        "TD",
        "KM",
        "CG",
        "CD",
        "CI",
        "DJ",
        "EG",
        "GQ",
        "ER",
        "SZ",
        "ET",
        "GA",
        "GM",
        "GH",
        "GN",
        "GW",
        "KE",
        "LS",
        "LR",
        "LY",
        "MG",
        "MW",
        "ML",
        "MR",
        "MU",
        "YT",
        "MA",
        "MZ",
        "NA",
        "NE",
        "NG",
        "RE",
        "RW",
        "SH",
        "ST",
        "SN",
        "SC",
        "SL",
        "SO",
        "ZA",
        "SS",
        "SD",
        "TZ",
        "TG",
        "TN",
        "UG",
        "EH",
        "ZM",
        "ZW",
    ]
)
ASIA = frozenset(
    [
        "AF",
        "BH",
        "BD",
        "BT",
        "BN",
        "KH",
        "CN",
        "CX",
        "CC",
        "HK",
        "IN",
        "ID",
        "IR",
        "IQ",
        "JP",
        "JO",
        "KZ",
        "KW",
        "KG",
        "LA",
        "LB",
        "MO",
        "MY",
        "MV",
        "MN",
        "MM",
        "NP",
        "KP",
        "OM",
        "PK",
        "PS",
        "PH",
        "QA",
        "SA",
        "SG",
        "KR",
        "LK",
        "SY",
        "TW",
        "TJ",
        "TH",
        "TL",
        "TM",
        "AE",
        "UZ",
        "VN",
        "YE",
        "IO",
    ]
)
EUROPE = frozenset(
    [
        "AL",
        "AD",
        "AM",
        "AT",
        "AZ",
        "BY",
        "BE",
        "BA",
        "BG",
        "HR",
        "CY",
        "CZ",
        "DK",
        "EE",
        "FO",
        "FI",
        "FR",
        "GE",
        "DE",
        "GI",
        "GR",
        "GG",
        "HU",
        "IS",
        "IE",
        "IM",
        "IL",
        "IT",
        "JE",
        "XK",
        "LV",
        "LI",
        "LT",
        "LU",
        "MT",
        "MD",
        "MC",
        "ME",
        "NL",
        "MK",
        "NO",
        "PL",
        "PT",
        "RO",
        "RU",
        "SM",
        "RS",
        "SK",
        "SI",
        "ES",
        "SJ",
        "SE",
        "CH",
        "TR",
        "UA",
        "GB",
        "VA",
    ]
)
NORTH_AMERICA = frozenset(
    [
        "AI",
        "AG",
        "AW",
        "BS",
        "BB",
        "BZ",
        "BM",
        "BQ",
        "CA",
        "KY",
        "CR",
        "CU",
        "CW",
        "DM",
        "DO",
        "SV",
        "GL",
        "GD",
        "GP",
        "GT",
        "HT",
        "HN",
        "JM",
        "MQ",
        "MX",
        "MS",
        "NI",
        "PA",
        "PR",
        "BL",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "SX",
        "TT",
        "TC",
        "US",
        "VG",
        "VI",
    ]
)
SOUTH_AMERICA = frozenset(
    ["AR", "BO", "BR", "CL", "CO", "EC", "FK", "GF", "GY", "PY", "PE", "SR", "UY", "VE"]
)
OCEANIA = frozenset(
    [
        "AS",
        "AU",
        "CK",
        "FJ",
        "PF",
        "GU",
        "KI",
        "MH",
        "FM",
        "NR",
        "NC",
        "NZ",
        "NU",
        "NF",
        "MP",
        "PW",
        "PG",
        "PN",
        "WS",
        "SB",
        "TK",
        "TO",
        "TV",
        "VU",
        "WF",
    ]
)

COUNTRY_NAME_ALIASES = {
    "Bolivia": "BO",
    "Brunei": "BN",
    "Cape Verde": "CV",
    "China": "CN",
    "Chinese Taipei": "TW",
    "Congo": "CG",
    "Czech Republic": "CZ",
    "Democratic Republic of the Congo": "CD",
    "East Timor": "TL",
    "Hong Kong, China": "HK",
    "Iran": "IR",
    "Kosovo": "XK",
    "Laos": "LA",
    "Macau, China": "MO",
    "Moldova": "MD",
    "North Korea": "KP",
    "Palestine": "PS",
    "Republic of Korea": "KR",
    "Russia": "RU",
    "South Korea": "KR",
    "Syria": "SY",
    "Taiwan": "TW",
    "Tanzania": "TZ",
    "United Kingdom": "GB",
    "United States": "US",
    "Venezuela": "VE",
    "Vietnam": "VN",
}


def normalise_continent(value: str | None) -> str:
    candidate = (value or "").removeprefix("_").strip()
    return candidate if candidate in CONTINENTS else ""


def country_code_from_name(name: str) -> str:
    cleaned = " ".join(name.split())
    if cleaned in COUNTRY_NAME_ALIASES:
        return COUNTRY_NAME_ALIASES[cleaned]
    try:
        return pycountry.countries.lookup(cleaned).alpha_2
    except LookupError as exc:
        raise ValueError(f"Unknown competitor country: {cleaned!r}") from exc


def continent_for_country_code(country_code: str | None) -> str:
    code = (country_code or "").upper()
    for continent, codes in (
        ("Africa", AFRICA),
        ("Asia", ASIA),
        ("Europe", EUROPE),
        ("North America", NORTH_AMERICA),
        ("South America", SOUTH_AMERICA),
        ("Oceania", OCEANIA),
    ):
        if code in codes:
            return continent
    return ""
